/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface Base64MockInterface extends ethers.utils.Interface {
  functions: {
    "encode(bytes)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "encode", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "encode", data: BytesLike): Result;

  events: {};
}

export class Base64Mock extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: Base64MockInterface;

  functions: {
    encode(value: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    "encode(bytes)"(
      value: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  encode(value: BytesLike, overrides?: CallOverrides): Promise<string>;

  "encode(bytes)"(value: BytesLike, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    encode(value: BytesLike, overrides?: CallOverrides): Promise<string>;

    "encode(bytes)"(
      value: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    encode(value: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    "encode(bytes)"(
      value: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    encode(
      value: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "encode(bytes)"(
      value: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
