/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface BridgeAMBMockInterface extends ethers.utils.Interface {
  functions: {
    "messageSender()": FunctionFragment;
    "relayAs(address,bytes,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "messageSender",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "relayAs",
    values: [string, BytesLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "messageSender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "relayAs", data: BytesLike): Result;

  events: {};
}

export class BridgeAMBMock extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: BridgeAMBMockInterface;

  functions: {
    messageSender(overrides?: CallOverrides): Promise<[string]>;

    "messageSender()"(overrides?: CallOverrides): Promise<[string]>;

    relayAs(
      target: string,
      data: BytesLike,
      sender: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "relayAs(address,bytes,address)"(
      target: string,
      data: BytesLike,
      sender: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  messageSender(overrides?: CallOverrides): Promise<string>;

  "messageSender()"(overrides?: CallOverrides): Promise<string>;

  relayAs(
    target: string,
    data: BytesLike,
    sender: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "relayAs(address,bytes,address)"(
    target: string,
    data: BytesLike,
    sender: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    messageSender(overrides?: CallOverrides): Promise<string>;

    "messageSender()"(overrides?: CallOverrides): Promise<string>;

    relayAs(
      target: string,
      data: BytesLike,
      sender: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "relayAs(address,bytes,address)"(
      target: string,
      data: BytesLike,
      sender: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    messageSender(overrides?: CallOverrides): Promise<BigNumber>;

    "messageSender()"(overrides?: CallOverrides): Promise<BigNumber>;

    relayAs(
      target: string,
      data: BytesLike,
      sender: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "relayAs(address,bytes,address)"(
      target: string,
      data: BytesLike,
      sender: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    messageSender(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "messageSender()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    relayAs(
      target: string,
      data: BytesLike,
      sender: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "relayAs(address,bytes,address)"(
      target: string,
      data: BytesLike,
      sender: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
