/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface Bytes32ToBytes32MapMockInterface extends ethers.utils.Interface {
  functions: {
    "at(uint256)": FunctionFragment;
    "contains(bytes32)": FunctionFragment;
    "get(bytes32)": FunctionFragment;
    "getWithMessage(bytes32,string)": FunctionFragment;
    "length()": FunctionFragment;
    "remove(bytes32)": FunctionFragment;
    "set(bytes32,bytes32)": FunctionFragment;
    "tryGet(bytes32)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "at", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "contains", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "get", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getWithMessage",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(functionFragment: "length", values?: undefined): string;
  encodeFunctionData(functionFragment: "remove", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "set",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "tryGet", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "at", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "contains", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "get", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getWithMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "length", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "remove", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "set", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tryGet", data: BytesLike): Result;

  events: {
    "OperationResult(bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OperationResult"): EventFragment;
}

export class Bytes32ToBytes32MapMock extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: Bytes32ToBytes32MapMockInterface;

  functions: {
    at(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, string] & { key: string; value: string }>;

    "at(uint256)"(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, string] & { key: string; value: string }>;

    contains(key: BytesLike, overrides?: CallOverrides): Promise<[boolean]>;

    "contains(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    get(key: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    "get(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getWithMessage(
      key: BytesLike,
      errorMessage: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "getWithMessage(bytes32,string)"(
      key: BytesLike,
      errorMessage: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    length(overrides?: CallOverrides): Promise<[BigNumber]>;

    "length()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    remove(key: BytesLike, overrides?: Overrides): Promise<ContractTransaction>;

    "remove(bytes32)"(
      key: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    set(
      key: BytesLike,
      value: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "set(bytes32,bytes32)"(
      key: BytesLike,
      value: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    tryGet(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean, string]>;

    "tryGet(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean, string]>;
  };

  at(
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, string] & { key: string; value: string }>;

  "at(uint256)"(
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, string] & { key: string; value: string }>;

  contains(key: BytesLike, overrides?: CallOverrides): Promise<boolean>;

  "contains(bytes32)"(
    key: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  get(key: BytesLike, overrides?: CallOverrides): Promise<string>;

  "get(bytes32)"(key: BytesLike, overrides?: CallOverrides): Promise<string>;

  getWithMessage(
    key: BytesLike,
    errorMessage: string,
    overrides?: CallOverrides
  ): Promise<string>;

  "getWithMessage(bytes32,string)"(
    key: BytesLike,
    errorMessage: string,
    overrides?: CallOverrides
  ): Promise<string>;

  length(overrides?: CallOverrides): Promise<BigNumber>;

  "length()"(overrides?: CallOverrides): Promise<BigNumber>;

  remove(key: BytesLike, overrides?: Overrides): Promise<ContractTransaction>;

  "remove(bytes32)"(
    key: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  set(
    key: BytesLike,
    value: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "set(bytes32,bytes32)"(
    key: BytesLike,
    value: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  tryGet(key: BytesLike, overrides?: CallOverrides): Promise<[boolean, string]>;

  "tryGet(bytes32)"(
    key: BytesLike,
    overrides?: CallOverrides
  ): Promise<[boolean, string]>;

  callStatic: {
    at(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, string] & { key: string; value: string }>;

    "at(uint256)"(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, string] & { key: string; value: string }>;

    contains(key: BytesLike, overrides?: CallOverrides): Promise<boolean>;

    "contains(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    get(key: BytesLike, overrides?: CallOverrides): Promise<string>;

    "get(bytes32)"(key: BytesLike, overrides?: CallOverrides): Promise<string>;

    getWithMessage(
      key: BytesLike,
      errorMessage: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "getWithMessage(bytes32,string)"(
      key: BytesLike,
      errorMessage: string,
      overrides?: CallOverrides
    ): Promise<string>;

    length(overrides?: CallOverrides): Promise<BigNumber>;

    "length()"(overrides?: CallOverrides): Promise<BigNumber>;

    remove(key: BytesLike, overrides?: CallOverrides): Promise<void>;

    "remove(bytes32)"(key: BytesLike, overrides?: CallOverrides): Promise<void>;

    set(
      key: BytesLike,
      value: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "set(bytes32,bytes32)"(
      key: BytesLike,
      value: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    tryGet(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean, string]>;

    "tryGet(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean, string]>;
  };

  filters: {
    OperationResult(result: null): EventFilter;
  };

  estimateGas: {
    at(index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "at(uint256)"(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    contains(key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    "contains(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    get(key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    "get(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getWithMessage(
      key: BytesLike,
      errorMessage: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getWithMessage(bytes32,string)"(
      key: BytesLike,
      errorMessage: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    length(overrides?: CallOverrides): Promise<BigNumber>;

    "length()"(overrides?: CallOverrides): Promise<BigNumber>;

    remove(key: BytesLike, overrides?: Overrides): Promise<BigNumber>;

    "remove(bytes32)"(
      key: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    set(
      key: BytesLike,
      value: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "set(bytes32,bytes32)"(
      key: BytesLike,
      value: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    tryGet(key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    "tryGet(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    at(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "at(uint256)"(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    contains(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "contains(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    get(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "get(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getWithMessage(
      key: BytesLike,
      errorMessage: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getWithMessage(bytes32,string)"(
      key: BytesLike,
      errorMessage: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    length(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "length()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    remove(
      key: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "remove(bytes32)"(
      key: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    set(
      key: BytesLike,
      value: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "set(bytes32,bytes32)"(
      key: BytesLike,
      value: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    tryGet(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "tryGet(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
