/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface TimersTimestampImplInterface extends ethers.utils.Interface {
  functions: {
    "getDeadline()": FunctionFragment;
    "isExpired()": FunctionFragment;
    "isPending()": FunctionFragment;
    "isStarted()": FunctionFragment;
    "isUnset()": FunctionFragment;
    "reset()": FunctionFragment;
    "setDeadline(uint64)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getDeadline",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isExpired", values?: undefined): string;
  encodeFunctionData(functionFragment: "isPending", values?: undefined): string;
  encodeFunctionData(functionFragment: "isStarted", values?: undefined): string;
  encodeFunctionData(functionFragment: "isUnset", values?: undefined): string;
  encodeFunctionData(functionFragment: "reset", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setDeadline",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getDeadline",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isExpired", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isPending", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isStarted", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isUnset", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "reset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDeadline",
    data: BytesLike
  ): Result;

  events: {};
}

export class TimersTimestampImpl extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: TimersTimestampImplInterface;

  functions: {
    getDeadline(overrides?: CallOverrides): Promise<[BigNumber]>;

    "getDeadline()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    isExpired(overrides?: CallOverrides): Promise<[boolean]>;

    "isExpired()"(overrides?: CallOverrides): Promise<[boolean]>;

    isPending(overrides?: CallOverrides): Promise<[boolean]>;

    "isPending()"(overrides?: CallOverrides): Promise<[boolean]>;

    isStarted(overrides?: CallOverrides): Promise<[boolean]>;

    "isStarted()"(overrides?: CallOverrides): Promise<[boolean]>;

    isUnset(overrides?: CallOverrides): Promise<[boolean]>;

    "isUnset()"(overrides?: CallOverrides): Promise<[boolean]>;

    reset(overrides?: Overrides): Promise<ContractTransaction>;

    "reset()"(overrides?: Overrides): Promise<ContractTransaction>;

    setDeadline(
      timestamp: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setDeadline(uint64)"(
      timestamp: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  getDeadline(overrides?: CallOverrides): Promise<BigNumber>;

  "getDeadline()"(overrides?: CallOverrides): Promise<BigNumber>;

  isExpired(overrides?: CallOverrides): Promise<boolean>;

  "isExpired()"(overrides?: CallOverrides): Promise<boolean>;

  isPending(overrides?: CallOverrides): Promise<boolean>;

  "isPending()"(overrides?: CallOverrides): Promise<boolean>;

  isStarted(overrides?: CallOverrides): Promise<boolean>;

  "isStarted()"(overrides?: CallOverrides): Promise<boolean>;

  isUnset(overrides?: CallOverrides): Promise<boolean>;

  "isUnset()"(overrides?: CallOverrides): Promise<boolean>;

  reset(overrides?: Overrides): Promise<ContractTransaction>;

  "reset()"(overrides?: Overrides): Promise<ContractTransaction>;

  setDeadline(
    timestamp: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setDeadline(uint64)"(
    timestamp: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    getDeadline(overrides?: CallOverrides): Promise<BigNumber>;

    "getDeadline()"(overrides?: CallOverrides): Promise<BigNumber>;

    isExpired(overrides?: CallOverrides): Promise<boolean>;

    "isExpired()"(overrides?: CallOverrides): Promise<boolean>;

    isPending(overrides?: CallOverrides): Promise<boolean>;

    "isPending()"(overrides?: CallOverrides): Promise<boolean>;

    isStarted(overrides?: CallOverrides): Promise<boolean>;

    "isStarted()"(overrides?: CallOverrides): Promise<boolean>;

    isUnset(overrides?: CallOverrides): Promise<boolean>;

    "isUnset()"(overrides?: CallOverrides): Promise<boolean>;

    reset(overrides?: CallOverrides): Promise<void>;

    "reset()"(overrides?: CallOverrides): Promise<void>;

    setDeadline(
      timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setDeadline(uint64)"(
      timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getDeadline(overrides?: CallOverrides): Promise<BigNumber>;

    "getDeadline()"(overrides?: CallOverrides): Promise<BigNumber>;

    isExpired(overrides?: CallOverrides): Promise<BigNumber>;

    "isExpired()"(overrides?: CallOverrides): Promise<BigNumber>;

    isPending(overrides?: CallOverrides): Promise<BigNumber>;

    "isPending()"(overrides?: CallOverrides): Promise<BigNumber>;

    isStarted(overrides?: CallOverrides): Promise<BigNumber>;

    "isStarted()"(overrides?: CallOverrides): Promise<BigNumber>;

    isUnset(overrides?: CallOverrides): Promise<BigNumber>;

    "isUnset()"(overrides?: CallOverrides): Promise<BigNumber>;

    reset(overrides?: Overrides): Promise<BigNumber>;

    "reset()"(overrides?: Overrides): Promise<BigNumber>;

    setDeadline(
      timestamp: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setDeadline(uint64)"(
      timestamp: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getDeadline(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getDeadline()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isExpired(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "isExpired()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isPending(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "isPending()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isStarted(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "isStarted()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isUnset(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "isUnset()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    reset(overrides?: Overrides): Promise<PopulatedTransaction>;

    "reset()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    setDeadline(
      timestamp: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setDeadline(uint64)"(
      timestamp: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
