/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { BadBeaconNotContract } from "../BadBeaconNotContract";

export class BadBeaconNotContract__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<BadBeaconNotContract> {
    return super.deploy(overrides || {}) as Promise<BadBeaconNotContract>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): BadBeaconNotContract {
    return super.attach(address) as BadBeaconNotContract;
  }
  connect(signer: Signer): BadBeaconNotContract__factory {
    return super.connect(signer) as BadBeaconNotContract__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BadBeaconNotContract {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as BadBeaconNotContract;
  }
}

const _abi = [
  {
    inputs: [],
    name: "implementation",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060dc8061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c80635c60da1b14602d575b600080fd5b60336047565b604051603e9190608d565b60405180910390f35b60006001905090565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006079826050565b9050919050565b6087816070565b82525050565b600060208201905060a060008301846080565b9291505056fea2646970667358221220e9e44fd3e3d2348b7c10adf3c9cda3eae6fcd8257113fb2887682d7a73c6e91a64736f6c63430008090033";
