/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { EtherReceiverMock } from "../EtherReceiverMock";

export class EtherReceiverMock__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<EtherReceiverMock> {
    return super.deploy(overrides || {}) as Promise<EtherReceiverMock>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): EtherReceiverMock {
    return super.attach(address) as EtherReceiverMock;
  }
  connect(signer: Signer): EtherReceiverMock__factory {
    return super.connect(signer) as EtherReceiverMock__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): EtherReceiverMock {
    return new Contract(address, _abi, signerOrProvider) as EtherReceiverMock;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "bool",
        name: "acceptEther",
        type: "bool",
      },
    ],
    name: "setAcceptEther",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610116806100206000396000f3fe608060405260043610601f5760003560e01c80634fea120c14604057603b565b36603b5760008054906101000a900460ff16603957600080fd5b005b600080fd5b348015604b57600080fd5b5060626004803603810190605e919060b8565b6064565b005b806000806101000a81548160ff02191690831515021790555050565b600080fd5b60008115159050919050565b6098816085565b811460a257600080fd5b50565b60008135905060b2816091565b92915050565b60006020828403121560cb5760ca6080565b5b600060d78482850160a5565b9150509291505056fea26469706673582212200477aad7423f55ae500ad244cf45c19be7607adffd0d01c6297caf8e92e4adf264736f6c63430008090033";
