/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IFxMessageProcessor } from "../IFxMessageProcessor";

export class IFxMessageProcessor__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFxMessageProcessor {
    return new Contract(address, _abi, signerOrProvider) as IFxMessageProcessor;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "stateId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "rootMessageSender",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "processMessageFromRoot",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
